[tool.poetry]
name = "fastid"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
authlib = "^1.3.0"
jinja2 = "^3.1.3"
pydantic-settings = "^2.1.0"
httpx = "^0.26.0"
itsdangerous = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
