services:
  nginx:
    image: nginx
    volumes:
      - './etc/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 80:80
    depends_on:
      - spam

  #cadvisor:
  #  image: gcr.io/cadvisor/cadvisor:latest
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - /:/rootfs:ro
  #    - /var/run:/var/run:rw
  #    - /sys:/sys:ro
  #    - /var/lib/docker/:/var/lib/docker:ro

  sausage:
    image: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./etc/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards

  tempo:
    depends_on:
      - grafana
    image: grafana/tempo
    command: [ "-target=all", "-storage.trace.backend=local", "-storage.trace.local.path=/var/tempo"]
    ports:
      - "4317:4317"
      - "4318:4318"

  loki:
    depends_on:
      - grafana
    image: grafana/loki
    ports:
      - "3100:3100"

  spam:
    build: "spam/."
    depends_on:
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_PYTHON_LOG_FORMAT="%(msg)s [span_id=%(span_id)s]"
      - OTEL_SERVICE_NAME=spam
      - OTEL_METRIC_EXPORT_INTERVAL=1000
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_PYTHON_LOG_CORRELATION=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8001:8001

  eggs:
    build: "eggs/."
    depends_on:
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_PYTHON_LOG_FORMAT="%(msg)s [span_id=%(span_id)s]"
      - OTEL_SERVICE_NAME=eggs
      - OTEL_METRIC_EXPORT_INTERVAL=1000
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_PYTHON_LOG_CORRELATION=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8002:8002
