[tool.taskipy.variables]
server = "root@137.184.189.141"

[tool.taskipy.tasks]
sync = { cmd = "rsync -a -v --progress . {server}:take3 --filter=':- .gitignore'", use_vars = true}
pre_deploy = 'task sync'
deploy = { cmd = "ssh {server} 'cd take3;docker compose down; docker compose up --build -d'", use_vars = true }
down = { cmd = "ssh {server} 'cd take3;docker compose down'", use_vars = true }
connect = {cmd = "ssh {server};", user_vars = true}
