global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  # - job_name: "cadvisor" 
  #  static_configs: 
  #  - targets: ["cadvisor:8080"]

  - job_name: spam
    static_configs:
      - targets: ["otel-collector:1234"]
